[2025-10-03T14:41:08.168+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_one_time_to_minio.check_generated_data manual__2025-10-03T14:41:07.173218+00:00 [queued]>
[2025-10-03T14:41:08.174+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_one_time_to_minio.check_generated_data manual__2025-10-03T14:41:07.173218+00:00 [queued]>
[2025-10-03T14:41:08.174+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-10-03T14:41:08.186+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): check_generated_data> on 2025-10-03 14:41:07.173218+00:00
[2025-10-03T14:41:08.192+0000] {standard_task_runner.py:57} INFO - Started process 612 to run task
[2025-10-03T14:41:08.197+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_one_time_to_minio', 'check_generated_data', 'manual__2025-10-03T14:41:07.173218+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/load_one_time_to_minio.py', '--cfg-path', '/tmp/tmp___8y_vw']
[2025-10-03T14:41:08.200+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask check_generated_data
[2025-10-03T14:41:08.250+0000] {task_command.py:415} INFO - Running <TaskInstance: load_one_time_to_minio.check_generated_data manual__2025-10-03T14:41:07.173218+00:00 [running]> on host 38cb3f89ee79
[2025-10-03T14:41:08.330+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_one_time_to_minio' AIRFLOW_CTX_TASK_ID='check_generated_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-03T14:41:07.173218+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-03T14:41:07.173218+00:00'
[2025-10-03T14:41:08.331+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-03T14:41:08.331+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "Проверяем данные..." && ls -la /opt/***/generated_data/']
[2025-10-03T14:41:08.347+0000] {subprocess.py:86} INFO - Output:
[2025-10-03T14:41:08.351+0000] {subprocess.py:93} INFO - Проверяем данные...
[2025-10-03T14:41:08.355+0000] {subprocess.py:93} INFO - total 12
[2025-10-03T14:41:08.355+0000] {subprocess.py:93} INFO - drwxr-xr-x 3    1000 1000 4096 Oct  3 14:40 .
[2025-10-03T14:41:08.356+0000] {subprocess.py:93} INFO - drwxrwxr-x 1 *** root 4096 Oct  3 13:23 ..
[2025-10-03T14:41:08.356+0000] {subprocess.py:93} INFO - drwxrwxr-x 2 root    root 4096 Oct  3 14:40 03-10-2025
[2025-10-03T14:41:08.356+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-03T14:41:08.386+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_one_time_to_minio, task_id=check_generated_data, execution_date=20251003T144107, start_date=20251003T144108, end_date=20251003T144108
[2025-10-03T14:41:08.447+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-03T14:41:08.476+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
